on:
    pull_request:
        types: [reopened]
    push:

name: e2e

jobs:
    test:
        name: e2e
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run end to end tests
              run: npm run test:e2e
              env:
                  E2E_DATABASE_URL: file:./dev.test.db
